/* eslint-disable -- auto-generated by bin/sync-locales.mjs */
import en from "javascript-time-ago/locale/en.json";
import eo from "javascript-time-ago/locale/eo.json";
import fr from "javascript-time-ago/locale/fr.json";
import de from "javascript-time-ago/locale/de.json";
import it from "javascript-time-ago/locale/it.json";
import es from "javascript-time-ago/locale/es.json";

export const TIME_AGO_LOCALE_DATA_BY_FILE = {
  "en": en,
  "eo": eo,
  "fr": fr,
  "de": de,
  "it": it,
  "es": es,
};
