#
# Github Actions for Serverless Framework
#
# Create AWS_KEY and AWS_SECRET secrets in Github repository settings
# If you're using env.yml file, store its content as ENV Github secret
#
# Master branch will be deployed as DEV and every new tag starting with "v**" (e.g. v1.0, v1.2, v2.0, etc) will be deployed as PROD
#
# Learn more: https://maxkostinevich.com/blog/how-to-deploy-serverless-applications-using-github-actions/
#

name: Deploy Dev
on:
  push:
    branches:
      - develop
  repository_dispatch:
    types: [dep_update_dev]
  workflow_dispatch:

jobs:
  deploy-dev:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: '18.x'

    - name: Install Serverless Framework
      run: npm install -g serverless

    - name: Serverless AWS authentication
      run: sls config credentials --provider aws --key ${{ secrets.AWS_KEY }} --secret ${{ secrets.AWS_SECRET }}

    # - name: Create env file
    #   run: | # cp sample.env.yml env.yml
    #     cat > env.yml << EOF
    #     ${{ secrets.ENV }}
    #     EOF

    - name: Create .npmrc
      run: echo "@abstractplay:registry=https://npm.pkg.github.com/" > .npmrc
    - run: echo "//npm.pkg.github.com/:_authToken=${{secrets.PAT_READ_PACKAGES}}" >> .npmrc

    - name: Install NPM dependencies
      run: npm ci

    - name: Build
      run: npm run build-dev
      env:
        CI: false

    - name: Invalidate
      run: aws cloudfront create-invalidation --distribution-id E2FD1T2JUN28HB --paths /*

    - name: Deploy
      run: serverless client deploy --no-confirm

    # Optional (to use with serverless-finch serverless plugin)
    #- name: Deploy assets to S3
    #  run: sls client deploy --no-delete-contents --no-confirm -s dev
