name: Test

on:
  pull_request:
  push:
    branches:
      - develop
      - main
  workflow_dispatch:

concurrency:
  group: test-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    uses: ./.github/workflows/ci-test.yml
    with:
      ap_deps_stage: dev
    secrets:
      PAT_READ_PACKAGES: ${{ secrets.PAT_READ_PACKAGES }}
